---
name: mysql-cis-baseline
title: CIS baseline for MySQL Server
maintainer: OpsTree
summary: The CIS MySQL Server InSpec profile.
license: Apache-2.0
Description: An InSpec Compliance Profile.
version: 0.1.0
supports:
  platform: os

attributes:
  - name: user
    description: 'username MSSQL DB Server'
    type: string
    value: 'root'

  - name: password
    description: 'password MSSQL DB Server'
    type: string
    value: 'N0Tweak$_@123!'

  - name: host
    description: 'hostname MSSQL DB Server'
    value: 'localhost'

  - name: port
    description: 'port MSSQL DB Server'
    type: numeric
    value: 3306

  - name: mysql_users
    description: 'List of mysql database users'
    type: array
    value: ['root']

  - name: is_mysql_server_slave_configured
    description: 'Set to true if the mysql server has a slave configured'
    type: boolean
    value: true

  - name: mysql_administrative_users
    description: 'List of mysql administrative users'
    type: array
    value: ['root']

  - name: mysql_users_allowed_modify_or_create
    description: 'List of mysql users allows to modify or create data structures'
    type: array
    value: ['root']
