---

# HAProxy Global settings
haproxy_maxconn: 2000
haproxy_notification_email: root
haproxy_notification_email_from: haproxy@{{ ansible_fqdn }}
haproxy_frontend_mode: http
haproxy_backend_mode: http
haproxy_backend_balance_method: roundrobin
haproxy_socket: /var/lib/haproxy/stats
haproxy_chroot: /var/lib/haproxy
haproxy_user: haproxy
haproxy_group: haproxy
haproxy_extra_global_vars: []
haproxy_node: '{{ ansible_hostname }}'
haproxy_processes: 1
haproxy_sysctl_file: /etc/sysctl.d/z0-haproxy.conf
haproxy_rsyslog_file: /etc/rsyslog.d/haproxy.conf
haproxy_logrotate_file: /etc/logrotate.d/haproxy
haproxy_firewalld_name: haproxy
haproxy_firewalld_file: '/etc/firewalld/services/{{ haproxy_firewalld_name }}.xml'
haproxy_bind_options: no-sslv3 no-tls-tickets
haproxy_bind_ciphers: ECDH+AESGCM:ECDH+CHACHA20:DH+AESGCM:ECDH+AES256:DH+AES256:ECDH+AES128:DH+AES:RSA+AESGCM:RSA+AES:!aNULL:!MD5:!DSS
haproxy_server_options: no-sslv3
haproxy_server_ciphers: ECDH+AESGCM:ECDH+CHACHA20:DH+AESGCM:ECDH+AES256:DH+AES256:ECDH+AES128:DH+AES:RSA+AESGCM:RSA+AES:!aNULL:!MD5:!DSS
haproxy_dh_param: 2048

# HAProxy Stats configuration
haproxy_enable_stats: true
haproxy_stats_port: 1936
haproxy_stats_username: "admin"
haproxy_stats_password: "197108"

# HAProxy Frontend settings
haproxy_frontends:
- name: default-fe
  process: 1
  binds:
  - "*:80"
  default_backend: default-be

# HAProxy Backend settings
haproxy_backends:
- name: default-be
  process: 1
  balance: roundrobin
  servers:

  - name: rp
    address: '194.58.88.133:{{ haproxy_stats_port }}'
    options: check






# Keepalived configuration
haproxy_enable_ha: true
haproxy_keepalived_vrrps:
- name: "VI_1"
  interface: "eth0"
  state: "MASTER"
  router_id: 51
  # peers:
  #    - 192.168.10.10
  #    - 192.168.10.20
  vips:
  - address: 194.58.88.133
    mask: 32

  
