---
- name: Install and configuring MySQL repository
  yum:
    name: "https://dev.mysql.com/get/{{ mysql_redhat_version }}-community-release-el7-9.noarch.rpm"
    state: present
  register: task_result
  until: task_result is succeeded
  retries: 5
  delay: 5

- name: Install MySQL server and its dependencies
  yum:
    name: ["mysql-server", "MySQL-python", "perl-DBD-MySQL"]
  state: present
  register: task_result
  until: task_result is succeeded
  retries: 5
  delay: 5
